### ISSUE TITLE
Get everything set up

### ISSUE THREAD

**Issue by ab-stha** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-londoners#1]
```[tasklist]
### Tasks
- [x] clone repo
- [x] install all packages
- [x] make a PostGres database from Render
- [x] link the pg database via the db connection string in env file
- [x] add port
- [x] run script that resets database
- [x] npm run dev
- [x] test that connection works with the hard coded 'im alive' status message
```
